# Generated by Django 6.0.1 on 2026-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_proyecto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imgPrincipal',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
    ]
