# Generated by Django 6.0.1 on 2026-02-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_proyecto_imgprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='repositorio',
            field=models.URLField(blank=True),
        ),
    ]
