# Generated by Django 6.0.1 on 2026-02-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_proyecto_repositorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='portfolio.proyecto')),
            ],
        ),
    ]
