# Generated by Django 6.0.1 on 2026-02-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tecnologiaproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='teconolgias',
            field=models.ManyToManyField(related_name='proyectos', to='portfolio.tecnologia'),
        ),
        migrations.DeleteModel(
            name='TecnologiaProyecto',
        ),
    ]
