# Generated by Django 6.0.1 on 2026-02-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_tecnologia_proyecto_teconolgias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='teconolgias',
            new_name='tecnologias',
        ),
    ]
