# Generated by Django 6.0.1 on 2026-02-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_teconolgias_proyecto_tecnologias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='repositorio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
