# Generated by Django 6.0.1 on 2026-02-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_proyecto_repositorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
